# Generated by Django 4.2.6 on 2023-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.DecimalField(decimal_places=2, max_digits=12, primary_key=True, serialize=False),
        ),
    ]
