# Generated by Django 4.2.6 on 2023-11-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_id_alter_category_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='lion.jpg', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='lion.jpg', null=True, upload_to='products/'),
        ),
    ]
